# -*- coding: utf-8 -*-
"""What the gallery in `png/verify.py` actually produced, asserted.

    python3 test_visual_verification.py     # exit 0 = all scenarios pass

The gallery draws the reader back onto the figure it read. Until this file
existed its only output was four PNGs, checked by a person looking at them - so
a reader that started answering about the neighbouring bar would have produced a
picture nobody was comparing with anything, and CI would have stayed green
because CI never ran it.

THE NUMBERS IT IS COMPARED WITH ARE NOT IN THIS FILE. They are in
`verification_truth.json`, and the SHA-256 below pins it: changing a truth value
and changing this constant are one diff, which is the property that makes the
comparison auditable. They were literals inside `png/verify.py`, where a drift
could be absorbed by editing the thing it was measured against.

WHAT IS ASSERTED IS PROVENANCE, NOT ONLY AGREEMENT. `397|FIG1` reads eighteen
cells and the package prices seven of them R4 - a number exists and the review
gate will not take it. A suite that asserted only "eighteen cells agree with the
eye" would pass while that mix silently changed, and the mix is the finding.

Both halves are gated, separately and for the same reason: the publisher rasters
and the 187-figure corpus are not in this repository.
"""
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "png"))
import raster_root as RR                                          # noqa: E402

FAILURES, PASSED = [], [0]


def check(name, ok, detail=""):
    print(("  ok   " if ok else "  FAIL ") + name + ("" if ok else "  <- " + detail))
    if ok:
        PASSED[0] += 1
    else:
        FAILURES.append(name)


def done():
    print()
    print("FDT_SCENARIOS_RUN=%d" % PASSED[0])
    print("%d scenarios run" % PASSED[0])
    if FAILURES:
        print("%d FAILED: %r" % (len(FAILURES), FAILURES))
        raise SystemExit(1)
    print("all scenarios passed")
    raise SystemExit(0)


#: The truth file this suite was written against.
TRUTH_SHA256 = "ab39f67d96db38a768bba770edfe8b25de18ed99745f7d5afe447863a8f4cacb"

import verify as V                                                # noqa: E402

# ------------------------------------------------------------------------
# WHAT A FRESH CLONE CAN CHECK. Everything above the gate below needs no
# publisher figure: the truth file is text, and the scatter fixtures are
# generated by `make_scatter_fixture.py` from twelve declared pairs and are in
# this repository because they are ours to publish. Until this section existed
# the whole file skipped in a clone, so a reader with no access to the figures
# got no evidence about the readers at all.
# ------------------------------------------------------------------------
print("the file the readings are compared with is the one this suite pins")
_got = hashlib.sha256(open(V.TRUTH_PATH, "rb").read()).hexdigest()
check("verification_truth.json hashes what this suite declares",
      _got == TRUTH_SHA256, "%s..." % _got[:16])
import json                                                       # noqa: E402
_doc = json.load(open(V.TRUTH_PATH, encoding="utf-8"))


def _keys(node):
    """Every field name in the document, at any depth."""
    if isinstance(node, dict):
        for key, value in node.items():
            yield str(key).lower()
            for inner in _keys(value):
                yield inner
    elif isinstance(node, list):
        for value in node:
            for inner in _keys(value):
                yield inner


# KEYS, NOT TEXT. The first draft searched the whole serialised document, and
# the sentence explaining that no reviewer is recorded contains the word
# "reviewer" - a check that fires on its own explanation. What may not exist is
# a FIELD: a truth file that grew one would be a confirmation nobody signed,
# recorded by the thing being checked.
_fields = set(_keys(_doc))
_forbidden = sorted(f for f in _fields
                    if any(t in f for t in ("reviewer", "orcid", "attestation",
                                            "inspection", "confirmed",
                                            "signature")))
check("  and it carries no reviewer, attestation or confirmation FIELD",
      _doc["status"] == "UNATTESTED_APPROXIMATE" and not _forbidden,
      "status %s, fields %r" % (_doc.get("status"), _forbidden))

print()
print("the scatter reader, on one drawing rendered six ways")
G5 = V.scatter_fixtures()
_R = G5["renderings"]
# EVERY PAIR AND NOTHING ELSE. The area bounds were absolute pixels once, and on
# publication 177 Figure 4 at 600 dpi they rejected every data point and returned
# four letters of the printed "r = 0.91" as the cloud: r = -0.47.
check("every rendering finds exactly the pairs its drawing declares",
      all(r["found"] == r["pairs"] for r in G5["rows"]),
      "%r" % [(r["name"], r["found"], r["pairs"]) for r in G5["rows"]])
check("  and every pair lands within 1% of the axis span",
      all(r["dx"] is not None and r["dx"] <= 0.01 and r["dy"] <= 0.01
          for r in G5["rows"]),
      "%r" % [(r["name"], r["dx"], r["dy"]) for r in G5["rows"]])
check("  and the association read is the association drawn, within 0.01",
      all(abs(r["assoc"] - r["true_r"]) < 0.01 for r in G5["rows"]),
      "%r" % [(r["name"], r["assoc"], r["true_r"]) for r in G5["rows"]])
# THE SCENARIO THE ABSOLUTE NUMBERS CANNOT PASS. One rendering read 22 marks and
# the other 4, off one drawing; agreement between renderings is the property
# that says the reader measured the figure rather than the page size.
check("  and the smallest and largest renderings agree with each other",
      G5["r_between"] is not None and G5["r_between"] < 0.01,
      "r differs by %r" % (G5["r_between"],))
# THE TRAP IS REAL WHERE THE RENDERING MAKES IT REAL, and asserted only there:
# at scale 1 the glyphs fall under the marker size and the mask does not hold
# them, which is exactly why the exclusion has to be DECLARED and not measured.
check("  and the printed statistics are marks until the panel declares them",
      all(_R[n]["with_annotation"] > _R[n]["pairs"]
          for n in _R if _R[n]["scale"] > 1)
      and _R["small"]["with_annotation"] == _R["small"]["pairs"],
      "%r" % {n: (_R[n]["scale"], _R[n]["with_annotation"], _R[n]["pairs"])
              for n in sorted(_R)})

print()
print("the twin-axis four-series fixture: a capability this package does not have")
G7 = V.twin_scatter_fixtures()
_T = G7["by_name"]
_SIZED = [n for n in _T if n != "micro"]
# THE DRAWING IS WHERE IT SAYS IT IS. A fixture whose declared centres are not
# inked is worse than none: every scenario a future reader passes against it
# would be measuring the generator's arithmetic.
check("every declared marker centre is inked, at every usable rendering",
      all(not _T[n]["missing"] for n in _SIZED),
      "%r" % {n: _T[n]["missing"][:1] for n in _SIZED if _T[n]["missing"]})
# AND AT 3 PX THE INK ITSELF GOES. An open marker that thin does not survive the
# render at all - which is a different finding from "the fill cannot be told",
# and the reason `micro` is excluded from the line above rather than fixed.
check("  and at 3 px some open markers leave no ink above the threshold",
      bool(_T["micro"]["missing"]),
      "%d missing" % len(_T["micro"]["missing"]))
# WHERE THE EVIDENCE FOR open/filled RUNS OUT, measured off the ink rather than
# declared by the generator. The interior ink ratio of the most-filled ring must
# stay below the least-filled disc for a threshold to exist at all.
check("  open and filled separate by interior ink down to 5 px",
      all(_T[n]["separates"] for n in _SIZED),
      "%r" % {n: (_T[n]["open_max"], _T[n]["filled_min"]) for n in _SIZED})
check("  and at 3 px they do not, so the fill must be refused and not guessed",
      not _T["micro"]["separates"],
      "open max %.3f, filled min %.3f"
      % (_T["micro"]["open_max"], _T["micro"]["filled_min"]))
check("  the reader refuses the four series at every rendering",
      all(G7["refusals"][n] == "multiple monochrome scatter series need "
                               "explicit marker routing" for n in G7["refusals"]),
      "%r" % (G7["refusals"],))
# TWO CALIBRATIONS, DELIBERATELY DIFFERENT. A fixture whose axes happened to
# share a scale would let a reader that ignores the right-hand one pass.
check("  and its two y calibrations differ by a factor of 2.8",
      abs(_T["s3"]["right_slope"] / _T["s3"]["left_slope"] - 2.8) < 0.05,
      "%.3f" % (_T["s3"]["right_slope"] / _T["s3"]["left_slope"]))
# THE SHORTCUT IS A FUNCTION OF THE RENDERING, not of the figure: 26 marks at
# one scale and 82 at another, off ONE drawing of 30 points, and no r near any
# series' own.
_counts = sorted(_T[n]["shortcut"] for n in _T)
check("  the one-series shortcut returns 26 to 82 marks for one 30-point drawing",
      (min(_counts), max(_counts)) == (26, 82),
      "%r" % (_counts,))
# AND ITS CORRELATION MOVES WITH THE PAGE SIZE. -0.653 to -0.804 off ONE
# drawing: a reading of a figure that changes when the figure is rendered larger
# is not a reading of the figure. NOT asserted as "far from every series' r" -
# at the 5 px rendering it lands 0.046 from L_FILLED_CIRCLE's -0.850, which is
# the more useful lesson: a plausible number is not a measured one, and nothing
# about the shortcut's output says which it is.
_rs = [_T[n]["shortcut_r"] for n in _T]
check("    and its correlation moves 0.15 across renderings of one drawing",
      max(_rs) - min(_rs) > 0.10,
      "%r" % {n: round(_T[n]["shortcut_r"], 3) for n in sorted(_T)})
check("    while no rendering's shortcut IS any series' correlation",
      all(min(abs(_T[n]["shortcut_r"] - v)
              for v in _T[n]["series_r"].values()) > 0.01 for n in _T),
      "%r" % {n: round(min(abs(_T[n]["shortcut_r"] - v)
                           for v in _T[n]["series_r"].values()), 4)
              for n in sorted(_T)})

print()
_rasters = all(RR.check("397_fig%d.jpeg" % n)[0] for n in (1, 3))
def stop_here(note, extra):
    """The scenarios above ran; the ones below need what is not here."""
    print(note)
    print("  %s" % extra)
    done()


if not _rasters:
    stop_here(RR.skip_note("397_fig3.jpeg"),
              "the rest of this gallery reads publisher figures")

# ONE GATE, NOT TWO. The segmentation half needs the corpus and the reading half
# needs the five rasters, and both come from the same private source - so this
# file runs all of its scenarios or none of them. Gating the two halves
# separately would give this suite THREE counts for two declared environments,
# and the count check downstream would then be comparing a number against an
# environment nobody named.
_missing = V.corpus_missing()
if _missing:
    stop_here(RR.corpus_note(*_missing),
              "the segmentation scenarios need it, and the figure half runs whole")

print("397 Fig. 3, the released BAR_MONO path, in two passes")
G1 = V.bars_397()
check("every declared cell was measured",
      G1["cells"] == G1["declared"] == 8,
      "%d measured, %d declared" % (G1["cells"], G1["declared"]))
# THE TWO PASSES ARE THE POINT. Pass one must name NOTHING - a row that arrives
# already named came from the per-panel reader, which is the path this gallery
# used to draw and `run_batch` does not dispatch.
check("  pass one named none of them",
      G1["unnamed_after_pass_one"] == G1["cells"],
      "%d of %d still unnamed" % (G1["unnamed_after_pass_one"], G1["cells"]))
check("  and pass two named all of them off the figure's own fills",
      G1["named_by_figure"] == G1["cells"],
      "%d of %d" % (G1["named_by_figure"], G1["cells"]))
check("  every cell agrees with the eye reading inside the stated tolerance",
      G1["compared"] == 8 and G1["worst"] <= G1["tolerance"],
      "%d compared, worst %.2f > %.2f" % (G1["compared"], G1["worst"] or -1,
                                          G1["tolerance"]))
check("  and every error bar was confirmed by its own stem",
      G1["stem_confirmed"] == G1["cells"],
      "%d of %d" % (G1["stem_confirmed"], G1["cells"]))

print()
print("397 Fig. 1, read back from the mark artifact the run wrote")
_RUN = V.pipeline_run()
G2 = V.lines_397(_RUN)
# THE PRODUCER IS IN THE CHAIN NOW. Reading the reader's return value catches a
# reader that writes a method its own ink does not support and nothing else: a
# mark re-stamped after measurement, a field lost in serialisation, a value
# joined to a mark it was not made from, a stale attestation - none of those
# exists in memory.
check("the panel's marks were read back from %s" % V.RB_SCHEMA,
      G2["schema"] == V.RB_SCHEMA, "%r" % (G2["schema"],))
check("  and both hashes recompute from the bytes on disk",
      G2["broken"] == [], "%r" % (G2["broken"][:3],))
check("  and every persisted mark joins to exactly one value row",
      G2["joined"] == G2["persisted"] == 18,
      "%d joined, %d persisted" % (G2["joined"], G2["persisted"]))
# EMITTED, NOT READ. Seven of these eighteen carry NONLOCAL_INTERPOLATION or
# EXTRAPOLATED_CURVE_INK: a number left the reader and the ink at that x did
# not produce it. "Read" is a claim about the figure; "emitted" is a fact about
# the run, and only the second one is this suite's to assert.
check("18 of the 24 declared cells emitted a value",
      (G2["emitted"], G2["declared"]) == (18, 24),
      "%d of %d" % (G2["emitted"], G2["declared"]))
# THE SIX ARE NOT AN ARBITRARY SIX. They are where the solid and dashed curves
# are one run of ink, and a reader that started answering there would be
# guessing which curve it had.
check("  and the six with no value are exactly the cells where the curves merge",
      G2["no_value"] == [("FLUID", "4:30"), ("FLUID", "5:00"), ("FLUID", "6:00"),
                         ("NON_FLUID", "4:30"), ("NON_FLUID", "5:00"),
                         ("NON_FLUID", "6:00")],
      "%r" % (G2["no_value"],))
check("  the provenance mix is the one this figure produces",
      G2["tiers"] == {"R0": 2, "R1": 9, "R4": 7, "NO_VALUE": 6},
      "%r" % (G2["tiers"],))
# ELEVEN METHOD-ELIGIBLE, NOT ELEVEN FINALIZABLE. The method tier is ONE gate.
# This publication does not say whether its error bars are SD or SEM, so nothing
# on it is ever accepted - which the scenario below measures rather than asserts
# from this comment.
# AND THE THIRD AXIS IS PRICED, not dropped. The tiers above come from
# `provenance.row_tier`, which is the row-shaped question - identity, value AND
# dispersion - and not from `review_tier`, which prices the MEAN alone. The
# gallery used the latter, so a cell whose SPREAD was reconstructed would have
# shown the tier of one whose spread was read. Every cell this reader emits is
# R0 on that axis today; pinning the distribution is what makes the first
# UNSTEMMED_CAP or RESTORED_MASKED_CAP arrive as a failing scenario rather than
# as a quiet change to a mixed number.
check("  the dispersion axis is priced too, and is R0 on all eighteen",
      G2["dispersion_tiers"] == {"R0": 18},
      "%r" % (G2["dispersion_tiers"],))
check("  eleven clear the method gate (R0-R3) and seven are R4 estimates",
      (G2["eligible"], G2["blocked"]) == (11, 7),
      "%d eligible, %d blocked" % (G2["eligible"], G2["blocked"]))
# AND THE TIERS ARE NOT THE READER'S WORD FOR IT. `png/verify.py` re-derives
# both methods from each mark's own recorded evidence through
# `provenance.expected_line_style_methods` and compares them with what the mark
# claims, which is what `run_batch` does before it will keep a value. A
# regression that wrote a cheaper method would otherwise be believed by the
# picture and by `review_tier` alike.
check("  and the persisted mark's evidence re-derives the methods beside it",
      G2["disagreed"] == [], "%r" % (G2["disagreed"],))
check("  every cell that emitted a value agrees with the eye inside the tolerance",
      G2["worst"] <= G2["tolerance"],
      "worst %.2f > %.2f" % (G2["worst"], G2["tolerance"]))

# WHERE THESE NUMBERS ACTUALLY STOP - off the same run's stamp, not off a
# second one. 397 does not say whether its error bars are SD or SEM, so machine
# QC passes nothing and the finalizer has nothing to accept. A gallery that
# implied eleven usable numbers would be overstating the same way "read" did.
check("  and the run that produced them accepted none, on either figure",
      G2["read_values"] > 0 and G2["qc_passed"] == 0 and G2["accepted"] == 0,
      "read %d, qc %d, accepted %d"
      % (G2["read_values"], G2["qc_passed"], G2["accepted"]))

print()
print("the segmentation half: panels found, and the ladder each one read")
if True:
    import tempfile
    _props = V.proposals_for([("475", "Fig. 2"), ("349", "Figure 3"),
                              ("464", "Fig. 2")],
                             os.path.join(tempfile.mkdtemp(prefix="fdt_vv_"),
                                          "proposals.csv"))
    for _pid, _fig, _name in (("475", "Fig. 2", "G3_segment_475fig2.png"),
                              ("349", "Figure 3", "G4_segment_349fig3.png")):
        _r = V.segmentation(_props, _pid, _fig,
                            os.path.join(HERE, "png", _name),
                            "%s %s" % (_pid, _fig))
        # THE COUNT IS THE MEASUREMENT. The proposer chooses its segmentation
        # mode by matching the number of axes counted by eye, so a run where the
        # two disagree has chosen a cut nobody validated.
        check("%s %s: the panels found are the axes counted by eye"
              % (_pid, _fig),
              _r["panels"] == _r["counted_by_eye"],
              "%d found, %d counted" % (_r["panels"], _r["counted_by_eye"]))
        check("  and every one of them read a validated tick ladder",
              _r["ladders"] == _r["panels"] and _r["statuses"] == ["LADDER_OK"],
              "%d ladders, statuses %r" % (_r["ladders"], _r["statuses"]))
        # AND THE CUT IS THE CUT. The two scenarios above are not independent of
        # each other or of the proposer: it CHOOSES its segmentation mode by
        # matching the panel count a person made, so a count that agrees is
        # partly a fit. A box can move, keep the count and keep the ladder, and
        # take a bar group out of the panel with it - which is what happened
        # once. This is boundary, spine, IoU and tick values against a recorded
        # good cut, and the residuals are printed on the picture.
        check("  and every box, spine and ladder is where the recorded cut put it",
              not _r["drift"], "%s" % "; ".join(_r["drift"][:3]))

print()
print("464 Fig. 2: a real four-series monochrome scatter")
G6 = V.scatter_real(_props)
# FOUR SERIES TOLD APART BY SHAPE AND FILL, which no shared threshold supplies.
check("the reader refuses the four series this figure draws, and says why",
      G6["refusal"] == "multiple monochrome scatter series need explicit "
                       "marker routing",
      "%r" % (G6["refusal"],))
# AND THIS IS WHAT THE REFUSAL IS WORTH. Asked for one monochrome series, the
# same panel returns the tick numerals, the right axis's label and the two
# dashed regression lines, broken into fragments a tenth of a marker's area.
check("  the one-series shortcut returns 247 marks, a tenth of a marker each",
      (G6["shortcut"], G6["area_median"]) == (247, 10.0),
      "%d marks, median area %r" % (G6["shortcut"], G6["area_median"]))
check("  and it reads ink past the end of the x axis",
      G6["x_max_read"] > G6["x_axis_max"],
      "read to %.2f on an axis ending at %g" % (G6["x_max_read"],
                                                G6["x_axis_max"]))
# THE NUMBER THE SHORTCUT WOULD HAVE PUBLISHED. Both clouds fall steeply; what
# comes back is no association at all, at P = 0.90. A refusal that prevents this
# is worth more than a reading that produces it.
check("  and reports no association where the figure shows two steep ones",
      abs(G6["assoc"]) < 0.05 and G6["p"] > 0.5,
      "r = %.3f, P = %.2f" % (G6["assoc"], G6["p"]))
# FINDING THE BOX IS NOT HAVING THE AXES. This asserted `panels == 1` against
# `declared_axes == 1` and called the axes accounted for - but `declared_axes`
# is a PANEL count, and this figure prints two y scales over one panel. One
# field was answering two questions, and the shape of the answer was "complete".
check("  one physical panel, and the figure prints two y scales over it",
      (G6["physical_panels"], G6["observed_y_axes"]) == (1, 2),
      "%d panel(s), %d y axis(es)"
      % (G6["physical_panels"], G6["observed_y_axes"]))
check("  of which one calibration is resolved, at a sub-pixel residual",
      G6["resolved_y_calibrations"] == 1 and G6["residual"] <= 0.5,
      "%d resolved, residual %.2f px"
      % (G6["resolved_y_calibrations"], G6["residual"]))
check("  and no series is read automatically, so nothing is offered",
      G6["automatic_point_series"] == 0,
      "%d series" % G6["automatic_point_series"])
# THE TERMINAL STATE, PINNED. Not "it skipped": a route, and the two findings
# that produced it, so "why is there no automatic value" and "what does a person
# do" are one record. The worklist reached the same place independently.
check("  the terminal route is MANUAL_WPD_TWIN_AXIS, and names both causes",
      G6["terminal_route"] == "MANUAL_WPD_TWIN_AXIS"
      and G6["terminal_causes"] == ["SCATTER_MONO_MULTISERIES_UNSUPPORTED",
                                    "SECONDARY_Y_AXIS_UNRESOLVED"],
      "%s %r" % (G6["terminal_route"], G6["terminal_causes"]))
check("    and the worklist routed it the same way, at target_axes 0",
      (G6["worklist_route"], G6["worklist_target_axes"])
      == ("DIGITIZE_TWIN_AXIS", 0),
      "%s, target_axes %d" % (G6["worklist_route"], G6["worklist_target_axes"]))

print()
print("the pictures themselves")
for _name in ("G1_read_397fig3.png", "G2_read_397fig1.png",
              "G5_scatter_fixtures.png", "G6_scatter_464fig2.png",
              "G7_twin_scatter.png"):
    _p = os.path.join(HERE, "png", _name)
    check("%s was written" % _name,
          os.path.exists(_p) and os.path.getsize(_p) > 50000,
          "%s" % (os.path.getsize(_p) if os.path.exists(_p) else "absent"))

done()
