# -*- coding: utf-8 -*-
"""Does the crop on disk come from the box in the draft? Cut it again and see.

    python3 roundtrip.py <run dir>          # every row; exit 0 only if all match

WHY THIS FILE EXISTS. On 2026-09-02 an agent drew every `Figure_BBox` on its
page with y measured from the bottom instead of the top. Nothing failed. The
mirrored box was a plausible rectangle on the same page, so 461 confident
verdicts were made about regions nobody had cut, and 336 rows were blocked on
them. Every gate in the harness passed, because every gate checked the sheet
against itself and none checked a box against the picture it claims to
describe.

This check does that one thing. It repeats the intake's own cut - the padded
box, then the blank border trimmed from the outside in - and compares the
result with the crop file pixel for pixel. A mirrored box, a shifted box, a
crop regenerated by a different version, a draft row edited by hand: each of
them fails here, on the first row, in a second.

THE FORMULA IS COPIED FROM `corpus_intake.crop_figure`, ON PURPOSE. Importing
it would tie the sheet to the repository root; copying it means the two can
drift - and this file is what notices when they do, because the corpus stops
matching. `PAD` and `INK` are the intake's `pad=8` and `_INK_LEVEL`.
"""
import csv
import io
import os
import sys

PAD = 8
INK = 235

#: `corpus_intake._THIN_CROP_FRACTION` and `_EDGE_INK_SHARE`. Copied for the
#: same reason `cut` copies the cutting formula: importing would tie the sheet
#: to the repository root, and the copy is what notices when the two drift -
#: `test_crop_truth.py` compares this module's grade with the intake's on the
#: real corpus, so a changed constant there fails here.
THIN_FRACTION = 0.12
EDGE_SHARE = 0.06


def _box(text):
    try:
        x0, y0, x1, y1 = [float(v) for v in str(text).split(",")]
    except ValueError:
        return None
    return (x0, y0, x1, y1)


def cut(page, row):
    """(image, pixel box) exactly as the intake would cut this row, or None.

    `page` is the opened page raster. The box is `Figure_BBox` in the RASTER's
    convention: y grows downward from the top, as it does in the file - the
    intake multiplies y by height/points and uses it as a row index, and so
    does this.
    """
    from PIL import Image                                   # noqa: F401
    import numpy as np
    box = _box(row.get("Figure_BBox"))
    try:
        pw, ph = float(row["Page_Width_Pt"]), float(row["Page_Height_Pt"])
    except (KeyError, ValueError):
        return None
    if not box or pw <= 0 or ph <= 0:
        return None
    x0, y0, x1, y1 = box
    sx, sy = page.width / pw, page.height / ph
    left = max(0, int(x0 * sx) - PAD)
    top = max(0, int(y0 * sy) - PAD)
    right = min(page.width, int(x1 * sx) + PAD)
    bottom = min(page.height, int(y1 * sy) + PAD)
    if right - left < 8 or bottom - top < 8:
        return None
    padded = page.crop((left, top, right, bottom))
    ink = np.asarray(padded.convert("L"), dtype=np.uint8) < INK
    if ink.any():
        rows = np.flatnonzero(ink.any(axis=1))
        cols = np.flatnonzero(ink.any(axis=0))
        inner = (int(cols[0]), int(rows[0]), int(cols[-1]) + 1, int(rows[-1]) + 1)
        padded = padded.crop(inner)
        left, top = left + inner[0], top + inner[1]
    if padded.width < 8 or padded.height < 8:
        return None
    return padded, (left, top, left + padded.width, top + padded.height)


def grade(image, page):
    """ACCEPTABLE / THIN_CROP / EDGE_CLIPPED for a crop this module just made.

    WHY A RECUT NEEDS THIS. `Crop_Quality_Status` is a MEASUREMENT OF A CROP -
    is it tall enough to be a figure, does the drawing run off its sides. When
    a person names a different box and the crop is cut again, the stored
    measurement describes a picture that no longer exists, and it is the last
    gate the sheet applies: 183 of the 210 blocked rows carry THIN_CROP or
    EDGE_CLIPPED, so without re-measuring, drawing a box on them would recut
    the picture and leave the row blocked anyway - the page would be asking
    people for answers it had already decided to ignore.

    Unlike an audit's finding, this one is not a judgement anybody made by
    looking; it is arithmetic, and the honest thing is to do it again on the
    new picture rather than let it lapse.

    `image` is the crop BEFORE its blank border is trimmed, because that is
    where the edge question still has an answer: after trimming, ink lies
    against every side by construction. `cut` returns the trimmed picture, so
    this takes the untrimmed one separately.
    """
    import numpy as np
    if page.height <= 0:
        return "NO_CROP"
    ink = np.asarray(image.convert("L"), dtype=np.uint8) < INK
    clipped = bool(ink.shape[1] >= 2 and ink.size
                   and (ink[:, 0].mean() >= EDGE_SHARE
                        or ink[:, -1].mean() >= EDGE_SHARE))
    if not ink.any():
        # NOT A FIGURE, WHATEVER ITS SIZE. The intake grades a blank rectangle
        # ACCEPTABLE - it measures height against the page and a blank crop is
        # as tall as any other - and never produces one, because its boxes come
        # from text and ink. A hand-drawn box can: somebody drags across the
        # margin. `box_would_open` promises that drawing opens the row, so an
        # empty rectangle must not be the way to collect that promise. This is
        # the one place this grade is deliberately stricter than the intake,
        # and it is unreachable for the intake's own crops (0 of 644 in run2).
        return "NO_CROP"
    rows = np.flatnonzero(ink.any(axis=1))
    cols = np.flatnonzero(ink.any(axis=0))
    trimmed = image.crop((int(cols[0]), int(rows[0]),
                          int(cols[-1]) + 1, int(rows[-1]) + 1))
    if trimmed.width < 8 or trimmed.height < 8:
        return "NO_CROP"
    if trimmed.height < THIN_FRACTION * page.height:
        return "THIN_CROP"
    return "EDGE_CLIPPED" if clipped else "ACCEPTABLE"


def _trim_for_mutant(image):
    """변이 검사가 '여백을 턴 뒤에 옆면을 본다'를 흉내 낼 때만 씁니다."""
    import numpy as np
    ink = np.asarray(image.convert("L"), dtype=np.uint8) < INK
    if not ink.any():
        return image
    rows = np.flatnonzero(ink.any(axis=1))
    cols = np.flatnonzero(ink.any(axis=0))
    return image.crop((int(cols[0]), int(rows[0]),
                       int(cols[-1]) + 1, int(rows[-1]) + 1))


def cut_and_grade(page, row):
    """(image, pixel box, quality) - `cut`, plus what the new crop is worth."""
    box = _box(row.get("Figure_BBox"))
    try:
        pw, ph = float(row["Page_Width_Pt"]), float(row["Page_Height_Pt"])
    except (KeyError, ValueError):
        return None
    if not box or pw <= 0 or ph <= 0:
        return None
    x0, y0, x1, y1 = box
    sx, sy = page.width / pw, page.height / ph
    left = max(0, int(x0 * sx) - PAD)
    top = max(0, int(y0 * sy) - PAD)
    right = min(page.width, int(x1 * sx) + PAD)
    bottom = min(page.height, int(y1 * sy) + PAD)
    if right - left < 8 or bottom - top < 8:
        return None
    untrimmed = page.crop((left, top, right, bottom))
    got = cut(page, row)
    if got is None:
        return None
    image, pixel_box = got
    return image, pixel_box, grade(untrimmed, page)


def page_rasters(raster_dir):
    """{page number: path} for the rasters in one document's folder.

    THE INTAKE'S OWN CONVENTION, read the way `corpus_intake` reads it:
    `pdftoppm` writes page-N.png and pads N to the document's page count -
    page-4.png in a nine-page paper, page-004.png in a 350-page book - so the
    number is parsed, never formatted. Three tools used to format
    "page-%d.png" themselves and would have found nothing in the book.
    """
    out = {}
    if not raster_dir or not os.path.isdir(raster_dir):
        return out
    for name in os.listdir(raster_dir):
        if not (name.startswith("page-") and name.endswith(".png")):
            continue
        try:
            out[int(name[len("page-"):-len(".png")])] = os.path.join(raster_dir, name)
        except ValueError:
            continue
    return out


def sibling_raster(raster_path, page):
    """The raster for `page` in the same document folder as `raster_path`."""
    return page_rasters(os.path.dirname(str(raster_path or ""))).get(int(page), "")


def check(row, root):
    """('MATCH'|'MISMATCH'|'NO_CROP'|'NO_PAGE'|'NO_CUT', detail) for one row."""
    from PIL import Image
    import numpy as np
    rel = str(row.get("Figure_Crop") or "").strip()
    raster = str(row.get("Page_Raster") or "").strip()
    if not rel:
        return "NO_CROP", ""
    crop_path = os.path.join(root, rel)
    if not os.path.exists(crop_path):
        return "NO_CROP", "파일 없음"
    if not raster or not os.path.exists(raster):
        return "NO_PAGE", ""
    # A file that does not decode is the DECODE stage's finding, reported
    # there by name. Here it is simply a row this check cannot speak to.
    try:
        page = Image.open(raster)
        page.load()
        disk = Image.open(crop_path)
        disk.load()
    except Exception as exc:                                # noqa: BLE001
        return "UNREADABLE", str(exc)[:60]
    got = cut(page, row)
    if got is None:
        return "NO_CUT", "인테이크라면 크롭을 내지 않았을 상자"
    image, pixel_box = got
    if disk.size != image.size:
        return "MISMATCH", "크기 %sx%s vs 다시 자른 %sx%s" % (
            disk.size + image.size)
    a = np.asarray(disk.convert("L"), dtype=np.int16)
    b = np.asarray(image.convert("L"), dtype=np.int16)
    diff = float(np.abs(a - b).mean())
    if diff > 0.5:
        return "MISMATCH", "평균 픽셀 차이 %.2f" % diff
    return "MATCH", "%d,%d,%d,%d" % pixel_box


def selfcheck(run, k=3):
    """Refuse to run a box-consuming tool whose boxes do not cut the crops.

    Called at the top of anything that draws or measures `Figure_BBox`. Three
    rows are enough: a wrong convention fails every row, and the cost of the
    check is a fraction of a second.
    """
    draft = list(csv.DictReader(io.open(
        os.path.join(run, "figure_intake_draft.csv"), encoding="utf-8")))
    seen = 0
    for row in draft:
        status, detail = check(row, run)
        if status in ("NO_CROP", "NO_PAGE", "NO_CUT", "UNREADABLE"):
            continue
        if status != "MATCH":
            raise SystemExit(
                "왕복 검사 실패: %s 행의 상자대로 다시 자른 그림이 크롭 파일과 "
                "다릅니다 (%s). 좌표 규약이나 크롭 세대가 어긋났으므로 이 도구를 "
                "돌리지 않습니다." % (row["Draft_ID"], detail))
        seen += 1
        if seen >= k:
            return seen
    if seen == 0:
        raise SystemExit("왕복 검사를 할 수 있는 행이 없습니다 (크롭과 페이지가 "
                         "함께 있는 행이 0)")
    return seen


def main(run):
    draft = list(csv.DictReader(io.open(
        os.path.join(run, "figure_intake_draft.csv"), encoding="utf-8")))
    out, counts = [], {}
    for row in draft:
        status, detail = check(row, run)
        counts[status] = counts.get(status, 0) + 1
        out.append({"Draft_ID": row["Draft_ID"], "Status": status,
                    "Crop_Pixel_Box": detail if status == "MATCH" else "",
                    "Detail": "" if status == "MATCH" else detail})
    target = os.path.join(run, "roundtrip.csv")
    with io.open(target, "w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(out[0]))
        w.writeheader()
        w.writerows(out)
    print("왕복 검사 %d행: %s" % (len(out), ", ".join(
        "%s %d" % kv for kv in sorted(counts.items()))))
    for r in out:
        if r["Status"] == "MISMATCH":
            print("  MISMATCH %s  %s" % (r["Draft_ID"], r["Detail"]))
    return 0 if counts.get("MISMATCH", 0) == 0 else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1]))
